[phases.setup]
nixPkgs = ["nodejs_24", "nginx"]

[phases.install]
cmds = ["npm ci --include=optional --force"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "nginx -c /app/nginx.runtime.conf -g 'daemon off;'"
