import {CostTransactionDetail,costReference} from './cost-transaction-detail.jsx';
import {ecMoney,ecCategory,ecSum,ecGroups,ecEvents,ecServices,ecMonth,ecDate,ecPct,ecColor,ecGrowth,ecAlerts,ecDocumentRows} from './cost-analysis-model.js';

export function ExecutiveSummary({rows,previous,month}) {
  const total=ecSum(rows),vehicles=ecGroups(rows,r=>r.placa),categories=ecGroups(rows,ecCategory),suppliers=ecGroups(rows,r=>r.fornecedor),change=month?null:ecGrowth(total,ecSum(previous));
  const cards=[['Custo total',ecMoney(total),`${rows.length} lançamentos nos filtros atuais`],['Variação no período',change===null?'Sem base comparável':`${change>0?'+':''}${ecPct(change)}`,month?'Remova o mês para comparar períodos':`Anterior: ${ecMoney(ecSum(previous))} · Diferença: ${ecMoney(total-ecSum(previous))}`,change>0?'attention':change<0?'positive':''],['Custo médio por veículo',vehicles.length?ecMoney(total/vehicles.length):'—',`${vehicles.length} veículos com lançamentos`],['Veículo com maior custo',vehicles[0]?.name||'—',vehicles[0]?ecMoney(vehicles[0].value):'Sem dados'],['Categoria principal',categories[0]?.name||'—',total>0?`${ecPct((categories[0]?.value||0)/total*100)} do total`:'Sem dados'],['Maior fornecedor',suppliers[0]?.name||'—',suppliers[0]?ecMoney(suppliers[0].value):'Sem dados']];
  return <section aria-label="Resumo executivo"><h2 className="ec-section-title">Resumo executivo</h2><div className="ec-summary">{cards.map(([label,value,note,tone])=><article key={label} className={`ec-stat ${tone||''}`}><span>{label}</span><strong title={value}>{value}</strong><small>{note}</small></article>)}</div></section>;
}
export function CostAlerts({rows,previous,month}) {const alerts=ecAlerts(rows,previous,month);return alerts.length?<section className="ec-alerts"><h2 className="ec-section-title">Pontos de atenção</h2><div>{alerts.map(a=><article key={a.label} className={a.attention?'attention':''}><small>{a.attention?'Atenção':'Informativo'} · {a.label}</small><p>{a.text}</p></article>)}</div></section>:null;}

export function CostEvolutionChart({months,selected,onSelect,compact=false}) {
  const [mode,setMode]=React.useState('total'),[hover,setHover]=React.useState(null);
  const all=months.flatMap(m=>m.rows), names=ecGroups(all,mode==='veiculo'?r=>r.placa:ecCategory).map(g=>g.name);
  const series=mode==='veiculo'?names.slice(0,5):names;
  const data=months.map(m=>{const groups=ecGroups(m.rows,mode==='veiculo'?r=>r.placa:ecCategory);const values=mode==='total'?[{name:'Total',value:ecSum(m.rows)}]:series.map(name=>({name,value:groups.find(g=>g.name===name)?.value||0}));if(mode==='veiculo'&&names.length>5) values.push({name:'Demais veículos',value:ecSum(m.rows.filter(r=>!series.includes(r.placa)))});return {...m,total:ecSum(m.rows),values};});
  const width=Math.max(700,months.length*76),height=280,left=66,top=20,bottom=42,plot=height-top-bottom;
  const max=Math.max(1,...data.map(m=>m.values.filter(g=>g.value>0).reduce((s,g)=>s+g.value,0)),...data.map(m=>m.total));
  const min=Math.min(0,...data.map(m=>m.values.filter(g=>g.value<0).reduce((s,g)=>s+g.value,0)),...data.map(m=>m.total));
  const y=value=>top+(max-value)/(max-min)*plot, step=(width-left-16)/Math.max(1,data.length), x=i=>left+step*(i+.5);
  const active=data.find(m=>m.key===hover);
  return <section className="ec-panel ec-chart"><div className="ec-panel-head"><div><h2>Evolução dos custos</h2><p>{compact?"Custos mensais deste veículo nos filtros atuais.":"Selecione um mês para detalhar. Meses das extremidades podem ser parciais."}</p></div>{!compact&&<div className="ec-segments" aria-label="Visão do gráfico">{[['total','Total'],['categoria','Por categoria'],['veiculo','Por veículo']].map(([key,label])=><button key={key} aria-pressed={mode===key} onClick={()=>setMode(key)}>{label}</button>)}</div>}</div>
    <div className="ec-chart-scroll"><svg viewBox={`0 0 ${width} ${height}`} style={{minWidth:compact?500:700}} role="group" aria-label="Custos mensais. Use Tab e Enter para selecionar um mês.">
      {[0,1,2,3,4].map(t=>{const value=min+(max-min)*t/4;return <g key={t}><line x1={left} x2={width-10} y1={y(value)} y2={y(value)} stroke="currentColor" opacity=".12"/><text x={left-8} y={y(value)+4} textAnchor="end" fill="currentColor" fontSize="11">{value.toLocaleString('pt-BR',{notation:'compact',maximumFractionDigits:1})}</text></g>;})}
      <text x="8" y="13" fill="currentColor" fontSize="10">R$</text>
      {data.map((m,i)=>{let positive=0,negative=0;return <g key={m.key} role={compact?undefined:"button"} tabIndex={0} aria-label={`${ecMonth(m.key)}: ${ecMoney(m.total)}`} aria-pressed={selected===m.key} onMouseEnter={()=>setHover(m.key)} onFocus={()=>setHover(m.key)} onClick={()=>onSelect?.(m.key)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect?.(m.key);}}} className="ec-chart-column">
        <rect x={x(i)-step/2+2} y={top} width={step-4} height={plot} fill={selected===m.key?'#689fff22':'transparent'}/>
        {m.values.map(v=>{const from=v.value>=0?positive:negative;if(v.value>=0)positive+=v.value;else negative+=v.value;return <rect key={v.name} x={x(i)-Math.min(36,step*.55)/2} y={y(Math.max(from,from+v.value))} width={Math.min(36,step*.55)} height={Math.abs(y(from+v.value)-y(from))} fill={mode==='total'?'#689fff':ecColor(v.name)}><title>{ecMonth(m.key)} · {v.name}: {ecMoney(v.value)}{m.total>0?` · ${ecPct(v.value/m.total*100)}`:''}</title></rect>;})}
        <text x={x(i)} y={height-14} textAnchor="middle" fill="currentColor" fontSize="11">{ecMonth(m.key)}</text>
      </g>;})}
      <polyline points={data.map((m,i)=>`${x(i)},${y(m.total)}`).join(' ')} fill="none" stroke="#e6edf7" strokeWidth="2" pointerEvents="none"/>{data.map((m,i)=><circle key={m.key} cx={x(i)} cy={y(m.total)} r="3" fill="#e6edf7" pointerEvents="none"/>)}
    </svg></div>
    <div className="ec-chart-legend"><span>○ Total mensal</span>{mode!=='total'&&[...series,...(mode==='veiculo'&&names.length>5?['Demais veículos']:[])].map(name=><span key={name}><i style={{background:ecColor(name)}}/>{name}</span>)}</div>
    <div className="ec-chart-readout" aria-live="polite">{active?<><b>{ecMonth(active.key)} · {ecMoney(active.total)}</b>{active.values.filter(v=>v.value!==0).map(v=><span key={v.name}>{v.name}: {ecMoney(v.value)}{active.total>0?` (${ecPct(v.value/active.total*100)})`:''}</span>)}</>:<span>Passe o cursor ou use Tab sobre um mês para conferir os valores.</span>}</div>
  </section>;
}

function CostRanking({title,items,onSelect,controls}) {const max=Math.max(1,...items.map(i=>Math.abs(i.value)));return <section className="ec-panel"><div className="ec-panel-head"><h2>{title}</h2>{controls}</div>{!items.length?<p className="muted">Sem dados comparáveis nos filtros atuais.</p>:<ol className="ec-ranking">{items.slice(0,10).map((item,index)=><li key={item.name}><button disabled={!onSelect} onClick={()=>onSelect?.(item.name)}><div className="ec-ranking-line"><span className="ec-rank-number">{index+1}</span><b>{item.name}</b><strong>{item.display||ecMoney(item.value)}</strong></div><small>{item.detail}</small><div className="ec-bar-track"><span style={{width:`${Math.abs(item.value)/max*100}%`,background:item.color||'#689fff'}}/></div></button></li>)}</ol>}</section>;}
export function VehicleCostRanking({rows,previous,month,onSelect}) {
  const [mode,setMode]=React.useState('total');const choices=[['total','Mais caros']];
  if(!month&&previous.length)choices.push(['growth','Maior crescimento']);
  if(rows.some(r=>ecCategory(r)==='Combustível'))choices.push(['fuel','Combustível']);
  if(rows.some(r=>ecCategory(r)==='Manutenção'))choices.push(['service','Manutenção']);
  const selected=choices.some(c=>c[0]===mode)?mode:'total', base=selected==='fuel'?rows.filter(r=>ecCategory(r)==='Combustível'):selected==='service'?rows.filter(r=>ecCategory(r)==='Manutenção'):rows;
  const total=ecSum(base),groups=ecGroups(base,r=>r.placa),prior=ecGroups(previous,r=>r.placa),average=groups.length?total/groups.length:0;
  const items=groups.map(g=>{const growth=ecGrowth(g.value,prior.find(p=>p.name===g.name)?.value);return {...g,growth,detail:`${total>0?ecPct(g.value/total*100):'—'} do custo selecionado${groups.length>1&&average>0?` · ${ecPct(Math.abs(g.value/average-1)*100)} ${g.value>=average?'acima':'abaixo'} da média de gasto`:''}`};});
  const ranking=selected==='growth'?items.filter(i=>i.growth!==null).sort((a,b)=>b.growth-a.growth).map(i=>({...i,detail:`${i.growth>0?'+':''}${ecPct(i.growth)} vs. período anterior · ${i.detail}`})):items;
  return <CostRanking title="Veículos que mais gastaram" items={ranking} onSelect={onSelect} controls={<select aria-label="Ordenação do ranking" value={selected} onChange={e=>setMode(e.target.value)}>{choices.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>}/>;
}
export function CostCategoryRanking({rows,onSelect}) {const total=ecSum(rows);return <CostRanking title="Participação por categoria" items={ecGroups(rows,ecCategory).map(g=>({...g,color:ecColor(g.name),detail:total>0?`${ecPct(g.value/total*100)} do total`:'—'}))} onSelect={onSelect}/>;}
export function SupplierRanking({rows,onSelect}) {const total=ecSum(rows);return <CostRanking title="Maiores fornecedores por custo" items={ecGroups(rows,r=>r.fornecedor).map(g=>{const related=rows.filter(r=>r.fornecedor===g.name),count=ecEvents(related);return {...g,detail:`${related.length} lançamentos · ${count} documentos/atendimentos · média ${ecMoney(count?g.value/count:0)}${total>0?` · ${ecPct(g.value/total*100)} do total`:''}`};})} onSelect={onSelect}/>;}

export function VehicleCostTable({rows,monthCount,onOpen}) {const groups=ecGroups(rows,r=>r.placa),total=ecSum(rows),average=groups.length?total/groups.length:0;return <section className="ec-panel"><div className="ec-panel-head"><div><h2>Comparativo de veículos</h2><p>Abra uma placa para conferir categorias, fornecedores e documentos.</p></div></div><div className="ec-table-scroll"><table className="ec-table"><thead><tr>{['Veículo','Custo total','Média mensal¹','Principal categoria','Participação','Atendimentos²','Comparação de gasto'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{groups.map(g=>{const related=rows.filter(r=>r.placa===g.name);return <tr key={g.name}><td><button className="ec-link" onClick={()=>onOpen(g.name)}>{g.name} ↗</button></td><td>{ecMoney(g.value)}</td><td>{ecMoney(g.value/Math.max(1,monthCount))}</td><td>{ecGroups(related,ecCategory)[0]?.name}</td><td>{total>0?ecPct(g.value/total*100):'—'}</td><td>{ecEvents(ecServices(related))}</td><td>{groups.length<2||average<=0?'Sem comparação':`${ecPct(Math.abs(g.value/average-1)*100)} ${g.value>=average?'acima':'abaixo'} da média`}</td></tr>;})}</tbody></table></div>{!groups.length&&<p>Sem veículos nos filtros selecionados.</p>}<p className="ec-footnote">¹ Meses selecionados, incluindo meses parciais e sem lançamentos. ² Estimativa por documento. Comparação de gasto não mede eficiência nem ajusta por tipo de veículo ou distância.</p></section>;}

export function CostTransactionsTable({rows}) {
  const [expanded,setExpanded]=React.useState(null);
  const [search,setSearch]=React.useState(''),[size,setSize]=React.useState(25),[page,setPage]=React.useState(0),[sort,setSort]=React.useState({key:'data',direction:-1});
  React.useEffect(()=>setPage(0),[rows,search,size]);
  const documents=React.useMemo(()=>ecDocumentRows(rows),[rows]);
  const filtered=documents.filter(r=>`${r.fornecedor} ${r.descricao} ${r.documento} ${costReference(r)}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
  const sorted=[...filtered].sort((a,b)=>sort.direction*(sort.key==='valor'?a.valor-b.valor:String(a[sort.key]||'').localeCompare(String(b[sort.key]||''),'pt-BR'))),pages=Math.max(1,Math.ceil(sorted.length/size)),safePage=Math.min(page,pages-1);
  return <section className="ec-panel"><div className="ec-panel-head"><div><h2>Detalhamento dos lançamentos</h2><p>{filtered.length} encontrados · {ecMoney(ecSum(filtered))}</p></div><input aria-label="Buscar lançamentos" type="search" placeholder="Buscar fornecedor, descrição ou documento" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="ec-table-scroll"><table className="ec-table"><thead><tr>{[['data','Data'],['placa','Placa'],['tipoCusto','Categoria ERP'],['fornecedor','Fornecedor'],['descricao','Descrição'],['documento','Documento'],['valor','Valor']].map(([key,label])=><th key={key} aria-sort={sort.key===key?(sort.direction===1?'ascending':'descending'):'none'}><button onClick={()=>{setSort({key,direction:sort.key===key?-sort.direction:1});setPage(0);}}>{label} {sort.key===key?(sort.direction===1?'↑':'↓'):'↕'}</button></th>)}<th>Detalhes</th></tr></thead><tbody>{sorted.slice(safePage*size,(safePage+1)*size).map((r,i)=><React.Fragment key={`${r.id}-${i}`}><tr><td>{ecDate(r.data)}</td><td>{r.placa}</td><td>{r.tipoCusto}</td><td>{r.fornecedor}</td><td>{r.descricao}</td><td>{costReference(r)}</td><td>{ecMoney(r.valor)}</td><td><button className="btn" aria-expanded={expanded===r.id} onClick={()=>setExpanded(expanded===r.id?null:r.id)}>{expanded===r.id?'Fechar':'Detalhar itens'}</button></td></tr>{expanded===r.id&&<tr><td colSpan={8}><CostTransactionDetail row={r}/></td></tr>}</React.Fragment>)}</tbody></table></div>{!filtered.length&&<p>Nenhum lançamento encontrado.</p>}<div className="ec-pagination"><label>Registros por página <select value={size} onChange={e=>setSize(Number(e.target.value))}>{[25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><span>{safePage+1} de {pages}</span><button className="btn" disabled={!safePage} onClick={()=>setPage(safePage-1)}>Anterior</button><button className="btn" disabled={safePage===pages-1} onClick={()=>setPage(safePage+1)}>Próxima</button></div></section>;
}

export function VehicleCostDrawer({plate,rows,months,onClose,onFilter}) {
  const ref=React.useRef(null);
  React.useEffect(()=>{const previous=document.activeElement;ref.current?.focus();function key(e){if(e.key==='Escape')onClose();if(e.key==='Tab'){const targets=ref.current?.querySelectorAll('button:not([disabled]), input, select, [tabindex="0"]');if(!targets?.length)return;const first=targets[0],last=targets[targets.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[onClose]);
  const related=rows.filter(r=>r.placa===plate),categories=ecGroups(related,ecCategory);
  return <div className="ec-drawer-overlay" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><aside className="ec-drawer" ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="ec-drawer-title"><header><div><small>Detalhamento do veículo</small><h2 id="ec-drawer-title">{plate}</h2></div><button className="btn" aria-label="Fechar detalhes" onClick={onClose}>✕</button></header><div className="ec-drawer-body"><p className="muted">Valores respeitam os filtros atuais da análise.</p><div className="ec-drawer-total"><span>Custo total</span><strong>{ecMoney(ecSum(related))}</strong><button className="btn primary" onClick={()=>{onFilter(plate);onClose();}}>Filtrar a página por este veículo</button></div><div className="ec-drawer-categories">{categories.map(c=><div key={c.name}><span style={{color:ecColor(c.name)}}>{c.name}</span><b>{ecMoney(c.value)}</b></div>)}</div><CostEvolutionChart months={months.map(m=>({...m,rows:m.rows.filter(r=>r.placa===plate)}))} compact/><SupplierRanking rows={related}/><CostTransactionsTable rows={related}/></div></aside></div>;
}
export function ServiceActivity({rows,months}) {const services=ecServices(rows),count=ecEvents(services);return <details className="ec-panel ec-activity"><summary>Atendimentos e abastecimentos <span>{count} atendimentos estimados · {ecEvents(rows.filter(r=>ecCategory(r)==='Combustível'))} abastecimentos/documentos</span></summary><p>Média por atendimento: <b>{count?ecMoney(ecSum(services)/count):'—'}</b></p><div className="ec-activity-months">{months.map(m=><div key={m.key}><span>{ecMonth(m.key)}</span><strong>{ecEvents(ecServices(m.rows))}</strong></div>)}</div><p className="ec-footnote">Contagem estimada por documento, empresa, fornecedor e veículo. Sem documento, cada lançamento conta individualmente.</p></details>;}
