function dfNum(value) { const n = Number(value); return Number.isFinite(n) ? n : 0; }
function dfBRL(value) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(dfNum(value)); }
function dfDate(value) { if (!value) return "-"; const text = String(value).slice(0, 10); if (!/^\d{4}-\d{2}-\d{2}$/.test(text)) return "-"; const [y, m, d] = text.split("-"); return `${d}/${m}/${y}`; }
function dfMonth(value, long = false) { if (!value) return "-"; const [y, m] = value.split("-"); const names = ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"]; return long ? `${names[Number(m) - 1]}/${y}` : `${names[Number(m) - 1]}/${y.slice(2)}`; }
function dfDaysUntil(value) { const today = new Date(); today.setHours(12, 0, 0, 0); return Math.round((new Date(`${String(value).slice(0, 10)}T12:00:00`) - today) / 86400000); }
function dfDueLabel(value) { const days = dfDaysUntil(value); if (days === 0) return "Hoje"; if (days === 1) return "Amanhã"; if (days > 1 && days <= 7) return `${days} dias`; if (days <= 30) return "Até 30 dias"; return ""; }

const DF_GROUPS = [["financeiro", "Dívidas financeiras", "#8b7cf6"], ["operacional", "Fornecedores / operacional", "#4f8fc9"], ["impostos", "Impostos", "#d69e45"], ["outros", "Outros", "#64748b"]];
const DfKpi = ({ label, value, sub, tone = "blue", onClick }) => <button className={`df-kpi ${tone}`} onClick={onClick}><span>{label}</span><strong>{value}</strong><small>{sub}</small></button>;

const DfMonthlyChart = ({ items = [], average = 0, onSelect }) => {
  const max = Math.max(1, average, ...items.map((item) => dfNum(item.total)));
  return <div className="df-chart-shell"><div className="df-chart-area"><div className="df-average-line" style={{ bottom: `${average / max * 100}%` }}><span>Média {dfBRL(average)}</span></div>{items.map((item) => <button className="df-month-bar" key={item.mes} onClick={() => onSelect(item)}><div className="df-chart-tooltip"><strong>{dfMonth(item.mes, true)}</strong><b>{dfBRL(item.total)}</b>{DF_GROUPS.map(([key, label, color]) => <span key={key}><i style={{ background: color }}/>{label}<em>{dfBRL(item.composicao?.[key])}</em></span>)}<small>{item.quantidade} títulos</small></div><b>{dfBRL(item.total)}</b><div className="df-stack" style={{ height: `${Math.max(2, dfNum(item.total) / max * 100)}%` }}>{DF_GROUPS.map(([key, , color]) => { const value = dfNum(item.composicao?.[key]); return value > 0 && <i key={key} style={{ height: `${value / dfNum(item.total) * 100}%`, background: color }}/>; })}</div><span>{dfMonth(item.mes)}</span><small>{item.quantidade} títulos</small></button>)}</div><div className="df-pressure-row">{items.map((item) => <button key={item.mes} className={item.pressao?.id || "normal"} onClick={() => onSelect(item)}><b>{dfMonth(item.mes).split("/")[0]}</b><span>{item.pressao?.label || "Normal"}</span></button>)}</div></div>;
};

const DfRanking = ({ items = [], kind, onSelect }) => {
  const max = Math.max(1, ...items.map((item) => dfNum(item.valor)));
  return <div className="df-ranking">{items.map((item, index) => <button key={item.nome} onClick={() => onSelect(item)}><div><span><i>{index + 1}</i><strong>{item.nome}</strong></span><b>{dfBRL(item.valor)}</b></div><div className="df-rank-track"><i style={{ width: `${dfNum(item.valor) / max * 100}%` }}/></div><small>{item.quantidade} {kind} · {item.percentual || 0}% do total</small></button>)}</div>;
};

const DfDrawer = ({ drawer, rows, onClose }) => {
  const [sort, setSort] = React.useState("vencimento");
  const sorted = rows.slice().sort((a, b) => sort === "valor" ? b.valor - a.valor : sort === "pessoa" ? a.pessoa.localeCompare(b.pessoa, "pt-BR") : a.vencimento.localeCompare(b.vencimento));
  const total = sorted.reduce((sum, row) => sum + dfNum(row.valor), 0);
  return <><button className="df-drawer-backdrop" aria-label="Fechar detalhes" onClick={onClose}/><aside className="df-drawer"><div className="df-drawer-head"><div><span>Detalhamento</span><h2>{drawer.title}</h2><small>{sorted.length} títulos · {dfBRL(total)}</small></div><button onClick={onClose}>×</button></div><div className="df-drawer-sort"><span>Ordenar:</span>{[["vencimento", "Vencimento"], ["valor", "Maior valor"], ["pessoa", "Fornecedor"]].map(([key, label]) => <button className={sort === key ? "active" : ""} key={key} onClick={() => setSort(key)}>{label}</button>)}</div><div className="df-drawer-list">{sorted.map((row) => <article key={row.id}><div><strong>{dfDate(row.vencimento)}</strong>{dfDueLabel(row.vencimento) && <span className="df-due-badge">{dfDueLabel(row.vencimento)}</span>}</div><h3>{row.pessoa}</h3><p>{row.categoria} · Documento {row.documento || "-"}</p><small>Empresa {row.empresa} · {row.origem}</small><b>{dfBRL(row.valor)}</b></article>)}{!sorted.length && <div className="muted">Nenhum título neste recorte.</div>}</div></aside></>;
};

const DespesasFuturas = () => {
  const [empresa, setEmpresa] = React.useState(""); const [search, setSearch] = React.useState(""); const [months, setMonths] = React.useState(12);
  const [filters, setFilters] = React.useState({ empresa: "", search: "", months: 12 });
  const [data, setData] = React.useState({ resumo: {}, mensal: [], financiamentos: {}, categorias: [], fornecedores: [], pontosAtencao: [], titulos: [] });
  const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState(""); const [drawer, setDrawer] = React.useState(null);
  React.useEffect(() => { let active = true; setLoading(true); setError(""); window.RB_API.getDespesasFuturas(filters).then((payload) => active && setData(payload || {})).catch((e) => active && setError(e?.message || "Não foi possível carregar as despesas futuras.")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [JSON.stringify(filters)]);
  const apply = (next = {}) => setFilters({ empresa, search, months, ...next }); const summary = data.resumo || {}; const financing = data.financiamentos || {}; const titles = data.titulos || [];
  const open = (title, filter = {}) => setDrawer({ title, filter });
  const drawerRows = !drawer ? [] : titles.filter((row) => { const f = drawer.filter; if (f.id && row.id !== f.id) return false; if (f.mes && !row.vencimento.startsWith(f.mes)) return false; if (f.grupo && row.grupo !== f.grupo) return false; if (f.categoria && row.categoria !== f.categoria) return false; if (f.pessoa && row.pessoa !== f.pessoa) return false; if (f.dias && (dfDaysUntil(row.vencimento) < 0 || dfDaysUntil(row.vencimento) >= f.dias)) return false; return true; });
  const peakDelta = summary.mediaMensal ? dfNum(summary.pico?.total) / dfNum(summary.mediaMensal) * 100 - 100 : 0;

  return <div className="view fc-view df-view"><div className="page-head"><div><h1>Despesas Futuras</h1><div className="sub">Contas a pagar, empréstimos, financiamentos e compromissos dos próximos 12 meses.</div></div><div className="actions"><div className="df-period-tabs">{[3, 6, 12].map((value) => <button className={months === value ? "active" : ""} key={value} onClick={() => { setMonths(value); apply({ months: value }); }}>{value} meses</button>)}</div><button className="btn" onClick={() => apply()}><Icon name="refresh"/> Atualizar</button></div></div>
    <div className="fc-filters df-filters card"><label>Empresa<input inputMode="numeric" value={empresa} placeholder="Todas" onChange={(e) => setEmpresa(e.target.value)}/></label><label>Busca<input value={search} placeholder="Fornecedor, categoria, documento..." onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === "Enter" && apply()}/></label><button className="btn primary" onClick={() => apply()}><Icon name="search"/> Aplicar</button><button className="btn" onClick={() => { setEmpresa(""); setSearch(""); setMonths(12); setFilters({ empresa: "", search: "", months: 12 }); }}>Limpar</button></div>
    {error && <div className="card" style={{ color: "var(--crit)", borderColor: "var(--crit)" }}>{error}</div>}{loading && <div className="card">Carregando planejamento financeiro...</div>}
    {!loading && !error && <><div className="df-kpi-grid"><DfKpi label={`Total próximos ${data.periodo?.meses || months} meses`} value={dfBRL(summary.total)} sub={`${summary.quantidade || 0} títulos programados`} onClick={() => open("Todos os compromissos")}/><DfKpi label="Próximos 30 dias" value={dfBRL(summary.proximos30)} sub={`${summary.proximos30Percentual || 0}% do total · ${summary.proximos30Quantidade || 0} títulos`} tone="warn" onClick={() => open("Vencimentos nos próximos 30 dias", { dias: 30 })}/><DfKpi label="Dívidas financeiras" value={dfBRL(summary.financeiro)} sub={`${summary.financeiroPercentual || 0}% dos compromissos futuros`} tone="purple" onClick={() => open("Dívidas financeiras", { grupo: "financeiro" })}/><DfKpi label="Pico de desembolso" value={dfBRL(summary.pico?.total)} sub={`${dfMonth(summary.pico?.mes, true)} · ${Math.abs(peakDelta).toFixed(0)}% ${peakDelta >= 0 ? "acima" : "abaixo"} da média`} tone={summary.pico?.pressao?.id || "blue"} onClick={() => open(`Compromissos de ${dfMonth(summary.pico?.mes, true)}`, { mes: summary.pico?.mes })}/><DfKpi label="Média mensal" value={dfBRL(summary.mediaMensal)} sub={`média dos próximos ${data.periodo?.meses || months} meses`}/></div>
    <section className="card df-forecast"><div className="section-head"><div><h2>Previsão de desembolso</h2><div className="muted">Composição mensal — clique em um mês para conferir os títulos</div></div><div className="df-chart-legend">{DF_GROUPS.map(([key, label, color]) => <span key={key}><i style={{ background: color }}/>{label}</span>)}</div></div><DfMonthlyChart items={data.mensal || []} average={summary.mediaMensal} onSelect={(item) => open(`Compromissos de ${dfMonth(item.mes, true)}`, { mes: item.mes })}/></section>
    {!!data.pontosAtencao?.length && <section className="card df-attention"><div className="section-head"><div><h2>Pontos de atenção</h2><div className="muted">Leitura automática baseada nos dados financeiros</div></div></div><div>{data.pontosAtencao.map((item, index) => <button key={`${item.titulo}-${index}`} className={item.tipo} onClick={() => open(item.titulo, item.filtro)}><Icon name="alert"/><span><strong>{item.titulo}</strong><small>{item.detalhe}</small></span><b>{dfBRL(item.valor)}</b></button>)}</div></section>}
    <div className="df-main-grid"><section className="card df-debt"><div className="section-head"><div><h2>Dívidas financeiras</h2><div className="muted">Empréstimos, financiamentos e consórcios</div></div><strong>{dfBRL(financing.total)}</strong></div><div className="df-debt-stats"><div><span>Saldo financeiro</span><b>{dfBRL(financing.total)}</b><small>{financing.percentual || 0}% do total</small></div><div><span>Maior parcela</span><b>{dfBRL(financing.maiorParcela?.valor)}</b><small>{financing.maiorParcela?.pessoa || "-"}</small></div><div><span>Próximo vencimento</span><b>{dfDate(financing.proximo?.vencimento)}</b><small>{dfBRL(financing.proximo?.valor)} · {financing.proximo?.pessoa || "-"}</small></div></div><h3>Ranking de credores</h3><DfRanking items={financing.credores || []} kind="parcelas" onSelect={(item) => open(item.nome, { pessoa: item.nome, grupo: "financeiro" })}/></section><section className="card df-schedule"><div className="section-head"><div><h2>Próximas parcelas</h2><div className="muted">Agenda dos compromissos financeiros</div></div><button className="btn" onClick={() => open("Todas as dívidas financeiras", { grupo: "financeiro" })}>Ver todas</button></div><div className="table-wrap"><table className="data-table compact"><thead><tr><th>Vencimento</th><th>Credor</th><th>Tipo</th><th>Documento</th><th className="num">Valor</th></tr></thead><tbody>{(financing.proximos || []).slice(0, 10).map((row) => <tr key={row.id} onClick={() => open(`Título ${row.documento || ""}`, { id: row.id })}><td><strong>{dfDate(row.vencimento)}</strong>{dfDueLabel(row.vencimento) && <span className="df-due-badge">{dfDueLabel(row.vencimento)}</span>}</td><td>{row.pessoa}</td><td>{row.categoria}</td><td>{row.documento || "-"}</td><td className="num"><strong>{dfBRL(row.valor)}</strong></td></tr>)}</tbody></table></div></section></div>
    <div className="df-main-grid"><section className="card"><div className="section-head"><div><h2>Maiores categorias</h2><div className="muted">Participação nos compromissos futuros</div></div></div><DfRanking items={data.categorias || []} kind="títulos" onSelect={(item) => open(item.nome, { categoria: item.nome })}/></section><section className="card"><div className="section-head"><div><h2>Principais fornecedores</h2><div className="muted">Concentração das contas futuras</div></div></div><DfRanking items={data.fornecedores || []} kind="títulos" onSelect={(item) => open(item.nome, { pessoa: item.nome })}/></section></div></>}
    {drawer && <DfDrawer drawer={drawer} rows={drawerRows} onClose={() => setDrawer(null)}/>}</div>;
};

window.DespesasFuturas = DespesasFuturas;
