function fcIso(date = new Date()) { return [date.getFullYear(), String(date.getMonth() + 1).padStart(2, "0"), String(date.getDate()).padStart(2, "0")].join("-"); }
function fcMonthStart() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-01`; }
function fcDaysAgo(days) { const d = new Date(); d.setDate(d.getDate() - days); return fcIso(d); }
function fcNum(value) { const n = Number(value); return Number.isFinite(n) ? n : 0; }
function fcBRL(value) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(fcNum(value)); }
function fcDate(value) { if (!value) return "-"; const text = String(value).slice(0,10); if (!/^\d{4}-\d{2}-\d{2}$/.test(text)) return "-"; const [y,m,d] = text.split("-"); return `${d}/${m}/${y}`; }

const FC_PERIODS = [
  { label: "Hoje", range: () => ({ start: fcIso(), end: fcIso() }) },
  { label: "Amanhã", range: () => { const d = new Date(); d.setDate(d.getDate() + 1); return { start: fcIso(d), end: fcIso(d) }; } },
  { label: "Próx. 7 dias", range: () => { const d = new Date(); d.setDate(d.getDate() + 7); return { start: fcIso(), end: fcIso(d) }; } },
  { label: "Próx. 15 dias", range: () => { const d = new Date(); d.setDate(d.getDate() + 15); return { start: fcIso(), end: fcIso(d) }; } },
  { label: "Próx. 30 dias", range: () => { const d = new Date(); d.setDate(d.getDate() + 30); return { start: fcIso(), end: fcIso(d) }; } },
  { label: "Este mês", range: () => ({ start: fcMonthStart(), end: fcIso() }) },
  { label: "Próximo mês", range: () => { const d = new Date(); const first = new Date(d.getFullYear(), d.getMonth() + 1, 1); const last = new Date(d.getFullYear(), d.getMonth() + 2, 0); return { start: fcIso(first), end: fcIso(last) }; } },
];

const FcKpi = ({ label, value, sub, tone, icon }) => <div className="cv-kpi" style={{ borderLeftColor: tone }}><div className="kpi-label"><Icon name={icon}/><span>{label}</span></div><div className="kpi-value">{value}</div><div className="muted fc-kpi-sub">{sub}</div></div>;

const FcChart = ({ items }) => {
  const max = Math.max(1, ...items.flatMap((x) => [fcNum(x.entradas), fcNum(x.saidas)]));
  const minAcc = Math.min(0, ...items.map((x) => fcNum(x.acumulado))); const maxAcc = Math.max(1, ...items.map((x) => fcNum(x.acumulado))); const span = Math.max(1, maxAcc - minAcc);
  const points = items.map((item, index) => `${items.length === 1 ? 50 : index / (items.length - 1) * 100},${8 + (maxAcc - fcNum(item.acumulado)) / span * 76}`).join(" ");
  return <div className="fc-chart"><svg className="fc-balance-line" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={points}/></svg>{items.map((item) => <div className="fc-chart-day" key={item.data} title={`${fcDate(item.data)} · Entradas ${fcBRL(item.entradas)} · Saídas ${fcBRL(item.saidas)} · Saldo ${fcBRL(item.saldo)} · Acumulado ${fcBRL(item.acumulado)}`}><div className="fc-chart-bars"><i className="in" style={{ height: `${Math.max(2, fcNum(item.entradas) / max * 100)}%` }}/><i className="out" style={{ height: `${Math.max(2, fcNum(item.saidas) / max * 100)}%` }}/></div><span>{String(item.data).slice(8,10)}</span></div>)}</div>;
};

const FluxoCaixa = () => {
  const [start, setStart] = React.useState(fcMonthStart());
  const [end, setEnd] = React.useState(fcIso());
  const [mode, setMode] = React.useState("ambos");
  const [empresa, setEmpresa] = React.useState("");
  const [search, setSearch] = React.useState("");
  const [filters, setFilters] = React.useState({ dataInicio: fcMonthStart(), dataFim: fcIso(), mode: "ambos" });
  const [data, setData] = React.useState({ summary: {}, evolution: [], categories: [], movements: [] });
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState("");
  const [page, setPage] = React.useState(1);
  const [movementFilter, setMovementFilter] = React.useState("todos");
  const [categoryFilter, setCategoryFilter] = React.useState("");
  const [sort, setSort] = React.useState({ key: "data", direction: "desc" });

  React.useEffect(() => { let active = true; setLoading(true); setError(""); window.RB_API.getFluxoCaixa({ ...filters, limit: 2000 }).then((p) => { if (active) { setData(p || {}); setPage(1); } }).catch((e) => active && setError(e?.message || "Não foi possível carregar o fluxo de caixa.")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [JSON.stringify(filters)]);
  const apply = (next = {}) => setFilters({ dataInicio: start, dataFim: end, mode, empresa, search, ...next });
  const shortcut = (item) => { const p = item.range(); setStart(p.start); setEnd(p.end); setFilters({ dataInicio: p.start, dataFim: p.end, mode, empresa, search }); };
  const s = data.summary || {};
  const categories = Array.isArray(data.categories) ? data.categories : [];
  const periodMovements = Array.isArray(data.movements) ? data.movements : [];
  const overdueMovements = Array.isArray(data.overdue?.movements) ? data.overdue.movements : [];
  const showingOverdue = movementFilter.startsWith("vencido");
  const allMovements = showingOverdue ? overdueMovements : periodMovements;
  const movements = allMovements.filter((row) => (!categoryFilter || row.categoria === categoryFilter) && (movementFilter === "todos" || movementFilter === row.tipo || movementFilter === row.natureza || (movementFilter === "vencido" && row.vencido) || (movementFilter === "vencido-receber" && row.vencido && row.tipo === "entrada") || (movementFilter === "vencido-pagar" && row.vencido && row.tipo === "saida"))).sort((a,b) => { const av = sort.key === "valor" ? fcNum(a.valor) : String(a[sort.key] || ""); const bv = sort.key === "valor" ? fcNum(b.valor) : String(b[sort.key] || ""); const result = typeof av === "number" ? av - bv : av.localeCompare(bv, "pt-BR"); return sort.direction === "asc" ? result : -result; });
  const pages = Math.max(1, Math.ceil(movements.length / 50));
  const visible = movements.slice((page - 1) * 50, page * 50);
  const maxCategory = Math.max(1, ...categories.map((x) => fcNum(x.valor)));
  const changeSort = (key) => { setSort((old) => ({ key, direction: old.key === key && old.direction === "desc" ? "asc" : "desc" })); setPage(1); };
  const comparisonText = (value) => value === null || value === undefined ? "Sem comparação histórica" : `${value >= 0 ? "↑" : "↓"} ${Math.abs(value).toFixed(1)}% realizado vs. período anterior`;
  const alerts = [
    fcNum(s.vencidoReceber) > 0 && { tone: "crit", text: `${fcBRL(s.vencidoReceber)} a receber vencidos`, action: () => { setMovementFilter("vencido-receber"); setCategoryFilter(""); setPage(1); } },
    fcNum(s.vencidoPagar) > 0 && { tone: "crit", text: `${fcBRL(s.vencidoPagar)} a pagar vencidos`, action: () => { setMovementFilter("vencido-pagar"); setCategoryFilter(""); setPage(1); } },
    fcNum(s.proximosSeteDias) !== 0 && { tone: "warn", text: `${fcBRL(Math.abs(s.proximosSeteDias))} de impacto líquido nos próximos 7 dias` },
    fcNum(s.menorSaldo) < 0 && { tone: "warn", text: `Menor saldo projetado no período: ${fcBRL(s.menorSaldo)}` },
    data.concentration?.clientes?.maior && { tone: "info", text: `${data.concentration.clientes.maior.pessoa} representa ${data.concentration.clientes.maior.percentual}% das entradas` },
  ].filter(Boolean).slice(0,5);

  return <div className="view fc-view">
    <div className="page-head"><div><h1>Fluxo de Caixa</h1><div className="sub">Entradas, saídas e compromissos financeiros por data efetiva ou vencimento.</div></div><div className="actions">{FC_PERIODS.map((p) => <button className="btn" key={p.label} onClick={() => shortcut(p)}>{p.label}</button>)}<button className="btn" onClick={() => apply()}><Icon name="refresh"/> Atualizar</button></div></div>
    <div className="fc-mode-tabs"><button className={mode === "realizado" ? "active" : ""} onClick={() => { setMode("realizado"); apply({ mode: "realizado" }); }}>Realizado</button><button className={mode === "previsto" ? "active" : ""} onClick={() => { setMode("previsto"); apply({ mode: "previsto" }); }}>Previsto</button><button className={mode === "ambos" ? "active" : ""} onClick={() => { setMode("ambos"); apply({ mode: "ambos" }); }}>Realizado + previsto</button></div>
    <div className="fc-filters card"><label>Data inicial<input type="date" value={start} onChange={(e) => setStart(e.target.value)}/></label><label>Data final<input type="date" value={end} onChange={(e) => setEnd(e.target.value)}/></label><label>Empresa<input inputMode="numeric" value={empresa} placeholder="Todas" onChange={(e) => setEmpresa(e.target.value)}/></label><label>Busca<input value={search} placeholder="Cliente, fornecedor, documento..." onChange={(e) => setSearch(e.target.value)}/></label><button className="btn primary" onClick={() => apply()}><Icon name="search"/> Aplicar</button><button className="btn" onClick={() => { setEmpresa(""); setSearch(""); setMode("ambos"); setFilters({ dataInicio: start, dataFim: end, mode: "ambos" }); }}>Limpar</button></div>
    {error && <div className="card" style={{ color: "var(--crit)", borderColor: "var(--crit)" }}>{error}</div>}{loading && <div className="card">Carregando fluxo de caixa...</div>}
    <div className="fc-kpis"><FcKpi label="Entradas do período" value={fcBRL(s.entradas)} sub={comparisonText(data.comparison?.entradas)} tone="#22c55e" icon="trending-up"/><FcKpi label="Saídas do período" value={fcBRL(s.saidas)} sub={comparisonText(data.comparison?.saidas)} tone="#ef4444" icon="money"/><FcKpi label="Movimentação líquida" value={fcBRL(s.saldo)} sub="Sem saldo bancário inicial" tone={fcNum(s.saldo) >= 0 ? "#22c55e" : "#ef4444"} icon="chart"/><FcKpi label="Carteira a receber vencida" value={fcBRL(s.vencidoReceber)} sub={`${data.overdue?.receberQuantidade || 0} títulos, sem corte por período`} tone={fcNum(s.vencidoReceber) ? "#f59e0b" : "#64748b"} icon="alert"/><FcKpi label="Carteira a pagar vencida" value={fcBRL(s.vencidoPagar)} sub={`${data.overdue?.pagarQuantidade || 0} títulos, sem corte por período`} tone={fcNum(s.vencidoPagar) ? "#ef4444" : "#64748b"} icon="clock"/></div>
    {!!alerts.length && <div className="fc-alerts card"><div className="section-head"><h2>Atenção</h2></div><div>{alerts.map((alert,index) => <button key={index} className={alert.tone} onClick={alert.action}><Icon name="alert"/><span>{alert.text}</span>{alert.action && <b>Ver →</b>}</button>)}</div></div>}
    <div className="fc-analysis"><div className="card"><div className="section-head"><h2>Evolução do caixa</h2><div className="fc-legend"><span className="in">Entradas</span><span className="out">Saídas</span><span className="balance">Saldo acumulado</span></div></div>{(data.evolution || []).length ? <FcChart items={data.evolution}/> : <div className="muted">Sem movimentações no período.</div>}</div><div className="card"><div className="section-head"><h2>Maiores impactos</h2><span className="muted">Clique para filtrar</span></div><div className="fc-impact-columns"><div><h3>Entradas</h3>{categories.filter((x) => x.tipo === "entrada").slice(0,5).map((item) => <button className="fc-category" key={`in-${item.categoria}`} onClick={() => { setCategoryFilter(item.categoria); setPage(1); }}><div><strong>{item.categoria}</strong><span>{item.lancamentos} lanç.</span></div><b className="entrada">{fcBRL(item.valor)}</b><i><em style={{ width: `${fcNum(item.valor) / maxCategory * 100}%` }}/></i></button>)}</div><div><h3>Saídas</h3>{categories.filter((x) => x.tipo === "saida").slice(0,5).map((item) => <button className="fc-category" key={`out-${item.categoria}`} onClick={() => { setCategoryFilter(item.categoria); setPage(1); }}><div><strong>{item.categoria}</strong><span>{item.lancamentos} lanç.</span></div><b className="saida">{fcBRL(item.valor)}</b><i><em style={{ width: `${fcNum(item.valor) / maxCategory * 100}%` }}/></i></button>)}</div></div></div></div>
    <div className="card"><div className="section-head"><div><h2>Previsão diária de caixa</h2><div className="muted">Movimentação acumulada sem saldo bancário inicial</div></div></div><div className="table-wrap"><table className="data-table compact"><thead><tr><th>Data</th><th className="num">Entradas</th><th className="num">Saídas</th><th className="num">Saldo do dia</th><th className="num">Saldo acumulado</th></tr></thead><tbody>{(data.evolution || []).map((day) => <tr key={day.data} className={fcNum(day.acumulado) < 0 ? "fc-negative-day" : ""}><td>{fcDate(day.data)}</td><td className="num">{fcBRL(day.entradas)}</td><td className="num">{fcBRL(day.saidas)}</td><td className="num">{fcBRL(day.saldo)}</td><td className="num">{fcBRL(day.acumulado)}</td></tr>)}</tbody></table></div></div>
    <div className="fc-risk-grid"><div className="card"><div className="section-head"><h2>Concentração financeira</h2></div><div className="fc-concentration"><div><span>Maior cliente</span><strong>{data.concentration?.clientes?.maior?.pessoa || "-"}</strong><b>{data.concentration?.clientes?.maior?.percentual || 0}% das entradas</b><small>Top 5: {data.concentration?.clientes?.top5Percentual || 0}%</small></div><div><span>Maior fornecedor</span><strong>{data.concentration?.fornecedores?.maior?.pessoa || "-"}</strong><b>{data.concentration?.fornecedores?.maior?.percentual || 0}% das saídas</b><small>Top 5: {data.concentration?.fornecedores?.top5Percentual || 0}%</small></div></div></div><div className="card"><div className="section-head"><h2>Carteira vencida completa</h2><button className="btn" onClick={() => { setMovementFilter("vencido"); setCategoryFilter(""); setPage(1); }}>Ver títulos</button></div><div className="fc-overdue-summary"><div><span>Saldo líquido vencido</span><strong>{fcBRL(s.vencidoLiquido)}</strong><small>receber menos pagar</small></div><div><span>Maior título</span><strong>{fcBRL(data.overdue?.maior?.valor)}</strong><small>{data.overdue?.maior?.pessoa || "-"}</small></div><div><span>Mais antigo</span><strong>{data.overdue?.maisAntigo?.diasAtraso || 0} dias</strong><small>{data.overdue?.maisAntigo?.pessoa || "-"}</small></div></div></div></div>
    <div className="card"><div className="section-head"><div><h2>{showingOverdue ? "Carteira vencida" : "Movimentações do período"}</h2><div className="muted">{showingOverdue ? "Todos os títulos abertos vencidos, sem corte pela data inicial" : "Valores realizados e títulos abertos conforme o modo selecionado"}</div></div><span className="muted">{movements.length} registros · Página {page} de {pages}</span></div><div className="fc-quick-filters">{[["todos","Todos do período"],["entrada","Entradas"],["saida","Saídas"],["realizado","Realizados"],["previsto","Previstos"],["vencido","Todos vencidos"],["vencido-receber","Receber vencidos"],["vencido-pagar","Pagar vencidos"]].map(([key,label]) => <button key={key} className={movementFilter === key ? "active" : ""} onClick={() => { setMovementFilter(key); setCategoryFilter(""); setPage(1); }}>{label}</button>)}{categoryFilter && <button className="active" onClick={() => setCategoryFilter("")}>{categoryFilter} ×</button>}</div><div className="table-wrap"><table className="data-table compact fc-table"><thead><tr><th><button onClick={() => changeSort("data")}>Data ↕</button></th><th><button onClick={() => changeSort("vencimento")}>Vencimento ↕</button></th><th>Tipo</th><th>Situação</th><th><button onClick={() => changeSort("categoria")}>Categoria ↕</button></th><th><button onClick={() => changeSort("pessoa")}>Cliente/Fornecedor ↕</button></th><th>Documento</th><th>Histórico</th><th className="num"><button onClick={() => changeSort("valor")}>Valor ↕</button></th></tr></thead><tbody>{visible.map((row,index) => <tr key={`${row.id}-${index}`}><td>{fcDate(row.data)}</td><td>{fcDate(row.vencimento)}</td><td><span className={`badge ${row.tipo === "entrada" ? "ok" : "crit"}`}>{row.tipo === "entrada" ? "Entrada" : "Saída"}</span></td><td><span className={`badge ${row.vencido ? "crit" : row.natureza === "realizado" ? "ok" : "info"}`}>{row.vencido ? `Vencido ${row.diasAtraso}d` : row.natureza === "realizado" ? "Realizado" : "Previsto"}</span></td><td>{row.categoria}</td><td>{row.pessoa}</td><td>{row.documento || "-"}</td><td title={row.historico}>{row.historico || "-"}</td><td className="num" style={{ color: row.tipo === "entrada" ? "var(--ok)" : "var(--crit)" }}>{fcBRL(row.valor)}</td></tr>)}{!visible.length && <tr><td colSpan="9" className="muted">Nenhuma movimentação encontrada.</td></tr>}</tbody></table></div>{pages > 1 && <div className="cv-pagination"><button className="btn" disabled={page === 1} onClick={() => setPage((p) => p - 1)}>Anterior</button><span>Página {page} de {pages}</span><button className="btn" disabled={page === pages} onClick={() => setPage((p) => p + 1)}>Próxima</button></div>}</div>
  </div>;
};

window.FluxoCaixa = FluxoCaixa;
